# Generated by Django 5.2.3 on 2025-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='classification_data',
            field=models.JSONField(default=list),
        ),
    ]
