# Generated by Django 5.2.3 on 2025-07-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_analysisreport_classification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='final_branch_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='final_statement_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
