# Generated by Django 5.2.3 on 2025-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysisreport_final_branch_coverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='required_mappings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
