# Generated by Django 5.2.3 on 2025-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_program_required_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='interface_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
